name: Pull Request - Check Protobuf - Go

on:
  pull_request:
    paths:
      - 'proto/**.proto'

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout source
        uses: actions/checout@v3
        with:
          ref: ${{ github.head:ref }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # or latest go version
          check-latest: false
          cache: true
      - name: Generate Go Source
        shell: bash
        run: |
          make pipeline-build
